### ISSUE TITLE
Wheel textures not showing up on 50K Daf rear wheels.

### ISSUE THREAD

**Issue by maurice825** [50k-Customs/Wheels-Pack#4]
Hello 50Keda,

I have been getting the issue of the tires not showing up in the store.
On the front wheels they work fine, and I can select them, but for the rear axles, they wont show up in the store.

I have tried changing mod-order, giving it priority, and having it load last, both dont work.

Two links are example images.
http://steamcommunity.com/sharedfiles/filedetails/?id=518269725
http://steamcommunity.com/sharedfiles/filedetails/?id=518269690

**Comment by ziangc** [comment]
Hey Maurice,

if you downloaded the wheels directly from github the issue will appear. i
faced a similar issue, and it turns out that the 'suitable for' is used by
the wheels  50keda created.

if you add the rims to the rear wheels using the 'suitable for' template it
should work.

regards.

On 14 September 2015 at 23:37, maurice825 notifications@github.com wrote:

> Hello 50Keda,
> 
> I have been getting the issue of the tires not showing up in the store.
> On the front wheels they work fine, and I can select them, but for the
> rear axles, they wont show up in the store.
> 
> I have tried changing mod-order, giving it priority, and having it load
> last, both dont work.
> 
> Two links are example images.
> http://steamcommunity.com/sharedfiles/filedetails/?id=518269725
> http://steamcommunity.com/sharedfiles/filedetails/?id=518269690
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/50k-Customs/Wheels-Pack/issues/4.

## 

Regards,
Zi'ang

**Comment by simon50keda** [comment]
haha easy there guys, I know about this problem and it's on to do list before release. I just simply wasn't able to come that far yet ;)

**Comment by maurice825** [comment]
Not a problem then, I guess I can do without my Goodyear tires for some time haha,
just wanted to let you know incase you didnt know or incase it was overlooked.

Closing issue, since the 50Keda knew about the issue

**Comment by mawie** [comment]
Hello,

I still have this issue with the latest version, if I choose one of the DAF SR rims for the rear axle of both vanilla DAF trucks. All the other combinations work fine.

If I choose one of the DAF SR rims, it shows the rim on the truck but i can only choose between one of the 3 default tires because the shop tells me, that I still have the standard rim on the truck!?

Image: http://abload.de/img/2015-09-16_000045qxh7.jpg

**Comment by simon50keda** [comment]
Well you are right this bug still appears  & I found out why!
In DAF rear wheels there was:
"accessory_rim_data : 50k.alcoa_daf.sr.rim"
instead of:
"accessory_rim_data : 50k.alcoa_daf.sr.rrim"

It will be fixed in next release ;)

**Comment by simon50keda** [comment]
Finally fixed with commit: https://github.com/50k-Customs/Wheels-Pack/commit/7044ab094ae9f87f5de7ff188372d6e18a6c497e

EDIT: workaround until new version is release: Select any other rear rim from my pack, select desired tyres, again select DAF SR rim. The tires will stay in place.
